server:
   port: 10006
spring: 
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lower-case-service-id: true
         routes:
            - id: baidu
              uri: https://www.baidu.com
              predicates: 
                  - Path=/baidu
            - id: first-service      
              uri: lb://first-service
              predicates:
                  - Path=/first-service   
         globalcores:
            coreConfiguration:
               allowerdOrigns: "https://docs.spring.io"
               allowerdMethods:
                  - GET
               allowerdMethods:
                  - Content-Type
