server:
   port: 10006
spring: 
   cloud:
      gateway:
         routes:
            - id: fisrt
              uri: https://www.baidu.com
              predicates: 
                  - Path=/
