server:
   port: 10006
spring: 
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lower-case-service-id: true
         routes:
            - id: fisrt
              uri: https://www.baidu.com
              predicates: 
                  - Path=/
